// Stories
export const SET_STORIES = "SET STORIES";

export const OPEN_STORY_MODAL = "OPEN STORY MODAL";

export const CLOSE_STORY_MODAL = "CLOSE STORY MODAL";

export const SET_MODAL_STORY = "SET MODAL STORY";

export const SET_TOP_COMMENTERS = "SET TOP COMMENTERS";

export const GET_COMMENTERS_PROGRESS = "GET COMMMENTERS PROGRESS";